<?php
/*=======================================================\
|                        FrontKanban                     |
|--------------------------------------------------------|
|   Creator: Phương                                      |
|   Date :   01-12-2017                                  |
|   Description: Frontaccounting Project Management Ext  |
|   Free software under GNU GPL                          |
|                                                        |
\=======================================================*/

function create_project() {
	
}

//--------------------------------------------------------------------------

function update_project() {
	
}

//--------------------------------------------------------------------------

function delete_project() {
	
}
