
<link href="../css/kanban.css" rel="stylesheet" type="text/css" />
	
<div id="wrapper">
	<div id="board"></div>
	<div class="clear"></div>

	<div id="navigation" class="navigation">
		<h5>Project members</h5>

	</div>
</div>

<script type="text/javascript" src="../js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="../js/jquery.dragsort-0.5.2.js" ></script>
<script type="text/javascript" src="../js/config.js" ></script>
<script type="text/javascript" src="../js/kanban.js" ></script>