<?php
/*=======================================================\
|                        FrontKanban                     |
|--------------------------------------------------------|
|   Creator: Phương                                      |
|   Date :   01-12-2017                                  |
|   Description: Frontaccounting Project Management Ext  |
|   Free software under GNU GPL                          |
|                                                        |
\=======================================================*/

function projects_list() {
	
}

//--------------------------------------------------------------------------

function projects_list_cells() {
	
}

//--------------------------------------------------------------------------

function projects_list_row() {
	
}
